apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: cecilia08/ticket-service:v5
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: cockroachdb-client.ticketing.svc.cluster.local
            - name: DB_USER
              value: ticketuser
            - name: DB_PASSWORD
              value: mypassword
            - name: DB_NAME
              value: ticketdb
            - name: DB_PORT
              value: "26257" 
