apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      initContainers:
        - name: wait-for-db
          image: cockroachdb/cockroach:v23.2.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for ticketdb..."
              
              # Wait until CockroachDB accepts SQL
              until cockroach sql --insecure --host=cockroachdb-client -e "SELECT 1;" >/dev/null 2>&1; do
                echo "CockroachDB not ready..."
                sleep 2
              done

              # Wait until `ticketdb` exists
              until cockroach sql --insecure --host=cockroachdb-client -e "SHOW DATABASES;" | grep -w ticketdb >/dev/null 2>&1; do
                echo "ticketdb not created yet..."
                sleep 2
              done

              echo "ticketdb exists! Starting service."

      containers:
        - name: ticket-service
          image: cecilia08/ticket-service:v8
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: ""
            - name: DB_HOST
              value: "cockroachdb-client.ticketing.svc.cluster.local"
            - name: DB_NAME
              value: "ticketdb"
            - name: DB_PORT
              value: "26257"

