apiVersion: apps/v1
kind: Deployment
metadata:
  name: waiting-room-service
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waiting-room-service
  template:
    metadata:
      labels:
        app: waiting-room-service
    spec:
      containers:
        - name: waiting-room-service
          image: cecilia08/waiting-room-service:latest
          imagePullPolicy: Always  
          ports:
            - containerPort: 8082
          env:
            - name: TICKET_SERVICE_URL
              value: "http://ticket-service:8081"

